name: Upload Artifact

on: workflow_dispatch
  
jobs:
  upload:
    name: Upload
    runs-on: ubuntu-latest
    steps:
      - name: creer le fichier
        run: echo "coucou toi" > artifact.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Artifact
          path: artifact.txt

  download:
    needs: upload
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v3
        with:
          name: Artifact
      - name: Lire le fichier
        run: cat artifact.txt