name:  push or pull ?
on: [push, pull_request]
env: 
   PUSH: c'est un push
   PULL: c'est un pull request
   
  
jobs:
  the_anwser_pull:
    # 条件放在这里，直接查看条件是否符合
    if: ${{github.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: pull
        run: echo "$PULL"
 
  the_anwser_push:
      if: ${{github.event_name == 'push'}}
      runs-on: ubuntu-latest 
      steps:     
        - name: push
          run: echo "$PUSH"  