name:  push or pull
on: [push, pull_request]
env: 
   PUSH: c'est un push
   PULL: c'est un pull request
   
  
jobs:
  the_anwser_pull:
    if: ${{gihtub.event_name == 'pull_request'}}
    runs-on: ubuntu-latest
    steps:
      - name: "c'est pull"
        run: echo $PULL
 
  the_anwser_push:
      if: ${{gihtub.event_name == 'push'}}
      runs-on: ubuntu-latest 
      steps:     
        - name: "hello push"
          run: echo $PUSH   