name: "Workflow need"

on: workflow_dispatch

jobs:
  
  job_first:
    runs-on: ubuntu-latest
    steps:
      - name: "job_first"
        run: echo "premier job exécuté"

  job_second:
    needs: [job_first]
    runs-on: ubuntu-latest
    steps:
      - name: "job_second"
        run: echo "sencond workflow exécuté"